server:
  port: 8082

spring:
    jpa.hibernate.ddl-auto: create
    jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/shop_online
    username: shop-administrator
    password: admin


